services:
  subscriber:
    build: ./subscriber
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PUBSUB_EMULATOR_HOST=pubsub:8085
      - GCLOUD_PROJECT=my-local-project
      - TOPIC_NAME=ordered-topic
      - SUBSCRIPTION_NAME=ordered-subscription
    depends_on:
      - redis
      - pubsub

  publisher:
    build: ./publisher
    environment:
      - PUBSUB_EMULATOR_HOST=pubsub:8085
      - GCLOUD_PROJECT=my-local-project
      - TOPIC_NAME=ordered-topic

  redis:
    image: "redis:7-alpine"

  pubsub:
    image: gcr.io/google.com/cloudsdktool/cloud-sdk:latest
    command: gcloud beta emulators pubsub start --project=my-local-project --host-port=0.0.0.0:8085
    ports:
      - "8085:8085"
